version: "3"

services:

  nginx:
    build: ./docker/nginx
    container_name: education_host
    volumes:
      - ./:/var/www/html
    ports:
      - ${APP_PORT}:80
    networks:
      - network

  php-fpm:
    build:
      context: ./docker/php-fpm
      args:
        WWWGROUP: ${WWWGROUP}
        WWWUSER: ${WWWUSER}
        PHP_INI_DIR: ${PHP_INI_DIR}
    container_name: education_web
    volumes:
      - ./:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    networks:
      - network

volumes:
  db-data:
    driver: local

networks:
  network:
    driver: bridge